// AUTO-GENERATED by scripts/upload-exam-prep.mjs from the filenames in
// exam-prep-source/ — do not hand-edit EXAM_PREP_BAGS, it gets overwritten
// every time that script runs. Add/rename PDFs in exam-prep-source/ and
// re-run the script instead.
//
// Each PDF is exactly one language and one grade (a Grade 10 Afrikaans pack
// and its English equivalent are two separate files/bags, not one bag with
// two names) — that's what lets the store show only English packs to
// English-medium children and only Afrikaans packs to Afrikaans-medium ones.
export type ExamPrepBag = {
  id: string
  title: string
  description: string
  grade: number
  language: 'en' | 'af'
  // 'zip' for multi-document packs (cheat sheet + practice test + memo
  // bundled together), 'pdf' for a single-document pack.
  fileExt: 'pdf' | 'zip'
  // Bags can be listed ahead of the file actually being uploaded — shows a
  // "Coming soon" state instead of a broken purchase/download flow.
  comingSoon?: boolean
}

// Flat price for now (per Divan — will likely change once real bags ship).
export const EXAM_PREP_BAG_PRICE = 49

export const EXAM_PREP_BAGS: ExamPrepBag[] = []

export function examPrepStoragePath(bagId: string, fileExt: 'pdf' | 'zip'): string {
  return `exam-prep-bags/${bagId}.${fileExt}`
}
