// AUTO-GENERATED by scripts/upload-exam-prep.mjs from the filenames in
// exam-prep-source/ — do not hand-edit EXAM_PREP_BAGS, it gets overwritten
// every time that script runs. Add/rename files in exam-prep-source/ and
// re-run the script instead.
//
// Each file is exactly one language and one grade (a Grade 10 Afrikaans
// pack and its English equivalent are two separate files/bags, not one bag
// with two names) — that's what lets the store show only English packs to
// English-medium children and only Afrikaans packs to Afrikaans-medium ones.
export type ExamPrepBag = {
  id: string
  title: string
  description: string
  grade: number
  language: 'en' | 'af'
  // 'zip' for multi-document packs (cheat sheet + practice test + memo
  // bundled together), 'pdf' for a single-document pack.
  fileExt: 'pdf' | 'zip'
  // Bags can be listed ahead of the file actually being uploaded — shows a
  // "Coming soon" state instead of a broken purchase/download flow.
  comingSoon?: boolean
}

// Base price per pack. Pro gets 20% off (rounded); Free (and guests, once
// they sign up) pay full price; Max gets every pack included free — that
// path never reaches checkout at all, see /api/exam-prep/checkout.
export const EXAM_PREP_BAG_PRICE = 99
export const EXAM_PREP_PRO_DISCOUNT = 0.2

export function examPrepPriceFor(tier: 'free' | 'pro' | 'max'): number {
  if (tier === 'pro') return Math.round(EXAM_PREP_BAG_PRICE * (1 - EXAM_PREP_PRO_DISCOUNT))
  return EXAM_PREP_BAG_PRICE
}

export const EXAM_PREP_BAGS: ExamPrepBag[] = [
  {
    id: "graad-10-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 10,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-11-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 11,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-12-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 12,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-4-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 4,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-5-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 5,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-6-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 6,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-7-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 7,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-8-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 8,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "graad-9-kwartaal-3-2026-eksamenpak",
    title: "Kwartaal 3 2026 Eksamenpak",
    description: "Alles wat jy nodig het om voorbereid vir jou Kwartaal 3-eksamen te wees: 'n volledige oefeneksamen in die presiese CAPS-formaat, 'n volledige memorandum sodat jy jou eie antwoorde kan nagaan en presies sien waar jy punte verloor het, en 'n opsommingsblad met die belangrikste formules en konsepte vir vinnige hersiening. Spesiaal saamgestel vir jou graad, in jou taal.",
    grade: 9,
    language: "af",
    fileExt: "zip",
  },
  {
    id: "grade-10-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 10,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-11-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 11,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-12-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 12,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-4-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 4,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-5-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 5,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-6-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 6,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-7-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 7,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-8-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 8,
    language: "en",
    fileExt: "zip",
  },
  {
    id: "grade-9-term-3-2026-exam-pack",
    title: "Term 3 2026 Exam Pack",
    description: "Everything you need to walk into your Term 3 exam prepared: a full practice exam in the exact CAPS format, a complete memo so you can mark your own answers and see precisely where you lost marks, and a one-page cheat sheet summarising the key formulas and concepts for quick revision. Built specifically for your grade, in your language.",
    grade: 9,
    language: "en",
    fileExt: "zip",
  },
]

export function examPrepStoragePath(bagId: string, fileExt: 'pdf' | 'zip'): string {
  return `exam-prep-bags/${bagId}.${fileExt}`
}
